// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/checkSMS/checkSMS.proto

package go_micro_service_sendSMS

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SMSType int32

const (
	SMSType_Register SMSType = 0
)

var SMSType_name = map[int32]string{
	0: "Register",
}

var SMSType_value = map[string]int32{
	"Register": 0,
}

func (x SMSType) String() string {
	return proto.EnumName(SMSType_name, int32(x))
}

func (SMSType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d819467b42ac65e7, []int{0}
}

type EheckStatus int32

const (
	EheckStatus_Fail   EheckStatus = 0
	EheckStatus_Succ   EheckStatus = 1
	EheckStatus_Expire EheckStatus = 2
)

var EheckStatus_name = map[int32]string{
	0: "Fail",
	1: "Succ",
	2: "Expire",
}

var EheckStatus_value = map[string]int32{
	"Fail":   0,
	"Succ":   1,
	"Expire": 2,
}

func (x EheckStatus) String() string {
	return proto.EnumName(EheckStatus_name, int32(x))
}

func (EheckStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d819467b42ac65e7, []int{1}
}

type Message struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_d819467b42ac65e7, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

type Request struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Type                 SMSType  `protobuf:"varint,2,opt,name=Type,proto3,enum=go.micro.service.sendSMS.SMSType" json:"Type,omitempty"`
	Code                 int32    `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_d819467b42ac65e7, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Request) GetType() SMSType {
	if m != nil {
		return m.Type
	}
	return SMSType_Register
}

func (m *Request) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

type Response struct {
	Status               EheckStatus `protobuf:"varint,1,opt,name=status,proto3,enum=go.micro.service.sendSMS.EheckStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_d819467b42ac65e7, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatus() EheckStatus {
	if m != nil {
		return m.Status
	}
	return EheckStatus_Fail
}

func init() {
	proto.RegisterEnum("go.micro.service.sendSMS.SMSType", SMSType_name, SMSType_value)
	proto.RegisterEnum("go.micro.service.sendSMS.EheckStatus", EheckStatus_name, EheckStatus_value)
	proto.RegisterType((*Message)(nil), "go.micro.service.sendSMS.Message")
	proto.RegisterType((*Request)(nil), "go.micro.service.sendSMS.Request")
	proto.RegisterType((*Response)(nil), "go.micro.service.sendSMS.Response")
}

func init() { proto.RegisterFile("proto/checkSMS/checkSMS.proto", fileDescriptor_d819467b42ac65e7) }

var fileDescriptor_d819467b42ac65e7 = []byte{
	// 269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xcd, 0x4b, 0xc4, 0x30,
	0x14, 0xc4, 0xdb, 0xb5, 0x5f, 0xfb, 0x94, 0xa5, 0x3c, 0x04, 0x8b, 0x20, 0xd4, 0x82, 0x50, 0x16,
	0x8c, 0x50, 0xf1, 0xe8, 0x49, 0x56, 0xf0, 0x50, 0x90, 0xc4, 0xa3, 0x97, 0x9a, 0x7d, 0x74, 0xeb,
	0x47, 0x53, 0x9b, 0x54, 0xf4, 0xbf, 0x97, 0x66, 0x8b, 0x78, 0xd9, 0xbd, 0x4d, 0xc2, 0x2f, 0x33,
	0xcc, 0x04, 0xce, 0xba, 0x5e, 0x19, 0x75, 0x25, 0x37, 0x24, 0xdf, 0x44, 0x29, 0xfe, 0x04, 0xb3,
	0xf7, 0x98, 0xd4, 0x8a, 0x7d, 0x34, 0xb2, 0x57, 0x4c, 0x53, 0xff, 0xd5, 0x48, 0x62, 0x9a, 0xda,
	0xb5, 0x28, 0x45, 0x36, 0x87, 0xb0, 0x24, 0xad, 0xab, 0x9a, 0xb2, 0x57, 0x08, 0x39, 0x7d, 0x0e,
	0xa4, 0x0d, 0x1e, 0x83, 0xdf, 0x6d, 0x54, 0x4b, 0x89, 0x9b, 0xba, 0xf9, 0x9c, 0x6f, 0x0f, 0x78,
	0x03, 0xde, 0xd3, 0x4f, 0x47, 0xc9, 0x2c, 0x75, 0xf3, 0x45, 0x71, 0xce, 0x76, 0x99, 0x32, 0x51,
	0x8a, 0x11, 0xe4, 0x16, 0x47, 0x04, 0x4f, 0xaa, 0x35, 0x25, 0x07, 0xa9, 0x9b, 0xfb, 0xdc, 0xea,
	0xec, 0x01, 0x22, 0x4e, 0xba, 0x53, 0xad, 0x26, 0xbc, 0x85, 0x40, 0x9b, 0xca, 0x0c, 0xda, 0xa6,
	0x2d, 0x8a, 0x8b, 0xdd, 0xc6, 0x2b, 0x5b, 0xcb, 0xc2, 0x7c, 0x7a, 0xb4, 0x3c, 0x81, 0x70, 0xca,
	0xc3, 0xa3, 0xd1, 0xb5, 0x6e, 0xb4, 0xa1, 0x3e, 0x76, 0x96, 0x97, 0x70, 0xf8, 0x8f, 0xc7, 0x08,
	0xbc, 0xfb, 0xaa, 0x79, 0x8f, 0x9d, 0x51, 0x89, 0x41, 0xca, 0xd8, 0x45, 0x80, 0x60, 0xf5, 0xdd,
	0x35, 0x3d, 0xc5, 0xb3, 0xe2, 0x19, 0xa2, 0xbb, 0x69, 0x35, 0x7c, 0x04, 0xdf, 0x2e, 0x88, 0x7b,
	0x4a, 0x4e, 0x5b, 0x9d, 0x66, 0xfb, 0x90, 0x6d, 0xc5, 0xcc, 0x79, 0x09, 0xec, 0x47, 0x5c, 0xff,
	0x06, 0x00, 0x00, 0xff, 0xff, 0x93, 0x59, 0x87, 0xfb, 0xa9, 0x01, 0x00, 0x00,
}
