// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/sendSMS/sendSMS.proto

package go_micro_service_sendSMS

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SMSType int32

const (
	SMSType_Register SMSType = 0
)

var SMSType_name = map[int32]string{
	0: "Register",
}

var SMSType_value = map[string]int32{
	"Register": 0,
}

func (x SMSType) String() string {
	return proto.EnumName(SMSType_name, int32(x))
}

func (SMSType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5ec8c1ccbe7f0955, []int{0}
}

type Message struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ec8c1ccbe7f0955, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

type Request struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	CodeLen              int32    `protobuf:"varint,2,opt,name=codeLen,proto3" json:"codeLen,omitempty"`
	Type                 SMSType  `protobuf:"varint,3,opt,name=Type,proto3,enum=go.micro.service.sendSMS.SMSType" json:"Type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ec8c1ccbe7f0955, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Request) GetCodeLen() int32 {
	if m != nil {
		return m.CodeLen
	}
	return 0
}

func (m *Request) GetType() SMSType {
	if m != nil {
		return m.Type
	}
	return SMSType_Register
}

type Response struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Code                 int32    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ec8c1ccbe7f0955, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Response) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func init() {
	proto.RegisterEnum("go.micro.service.sendSMS.SMSType", SMSType_name, SMSType_value)
	proto.RegisterType((*Message)(nil), "go.micro.service.sendSMS.Message")
	proto.RegisterType((*Request)(nil), "go.micro.service.sendSMS.Request")
	proto.RegisterType((*Response)(nil), "go.micro.service.sendSMS.Response")
}

func init() { proto.RegisterFile("proto/sendSMS/sendSMS.proto", fileDescriptor_5ec8c1ccbe7f0955) }

var fileDescriptor_5ec8c1ccbe7f0955 = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0xb7, 0xda, 0x35, 0xee, 0x20, 0x22, 0x83, 0x60, 0xd0, 0x4b, 0xcd, 0xa9, 0x78, 0x88,
	0xb0, 0xea, 0xbf, 0xb0, 0x08, 0x89, 0x27, 0x6f, 0xda, 0x1d, 0x6a, 0x0f, 0x26, 0x31, 0x53, 0x05,
	0xff, 0xbd, 0x24, 0xcd, 0x1e, 0xb7, 0xa7, 0xcc, 0x4b, 0x1e, 0xef, 0x7b, 0x19, 0xb8, 0x09, 0xd1,
	0x4f, 0xfe, 0x9e, 0xc9, 0xed, 0x6c, 0x67, 0xf7, 0xa7, 0xce, 0xb7, 0x28, 0x07, 0xaf, 0xbf, 0xc6,
	0x3e, 0x7a, 0xcd, 0x14, 0x7f, 0xc7, 0x9e, 0x74, 0x79, 0x57, 0x1b, 0x10, 0x1d, 0x31, 0xbf, 0x0f,
	0xa4, 0x02, 0x08, 0x43, 0xdf, 0x3f, 0xc4, 0x13, 0x5e, 0xc2, 0x3a, 0x7c, 0x7a, 0x47, 0xb2, 0x6a,
	0xaa, 0x76, 0x63, 0x66, 0x81, 0x12, 0x44, 0xef, 0x77, 0xf4, 0x4c, 0x4e, 0x1e, 0x35, 0x55, 0xbb,
	0x36, 0x7b, 0x89, 0x4f, 0x50, 0xbf, 0xfe, 0x05, 0x92, 0xc7, 0x4d, 0xd5, 0x9e, 0x6f, 0x6f, 0xf5,
	0x21, 0x9c, 0xb6, 0x9d, 0x4d, 0x46, 0x93, 0xed, 0xea, 0x11, 0x4e, 0x0d, 0x71, 0xf0, 0x8e, 0xe9,
	0x00, 0x12, 0xa1, 0x4e, 0x8c, 0xc2, 0xcb, 0xf3, 0xdd, 0x15, 0x88, 0x12, 0x83, 0x67, 0x29, 0x60,
	0x18, 0x79, 0xa2, 0x78, 0xb1, 0xda, 0xbe, 0x81, 0xb0, 0x33, 0x07, 0x5f, 0xa0, 0x4e, 0x23, 0x2e,
	0x54, 0x29, 0x7f, 0xbd, 0x56, 0x4b, 0x96, 0xb9, 0x9c, 0x5a, 0x7d, 0x9c, 0xe4, 0x45, 0x3e, 0xfc,
	0x07, 0x00, 0x00, 0xff, 0xff, 0xd3, 0xc4, 0x3c, 0xaf, 0x67, 0x01, 0x00, 0x00,
}
