// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/sendSMS/sendSMS.proto

package go_micro_service_sendSMS

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ec8c1ccbe7f0955, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

type Request struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	MsgTmp               string   `protobuf:"bytes,2,opt,name=msgTmp,proto3" json:"msgTmp,omitempty"`
	Code                 int32    `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	CodeLen              int32    `protobuf:"varint,4,opt,name=codeLen,proto3" json:"codeLen,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ec8c1ccbe7f0955, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Request) GetMsgTmp() string {
	if m != nil {
		return m.MsgTmp
	}
	return ""
}

func (m *Request) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Request) GetCodeLen() int32 {
	if m != nil {
		return m.CodeLen
	}
	return 0
}

type Response struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Code                 int32    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ec8c1ccbe7f0955, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Response) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func init() {
	proto.RegisterType((*Message)(nil), "go.micro.service.sendSMS.Message")
	proto.RegisterType((*Request)(nil), "go.micro.service.sendSMS.Request")
	proto.RegisterType((*Response)(nil), "go.micro.service.sendSMS.Response")
}

func init() { proto.RegisterFile("proto/sendSMS/sendSMS.proto", fileDescriptor_5ec8c1ccbe7f0955) }

var fileDescriptor_5ec8c1ccbe7f0955 = []byte{
	// 202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x50, 0xc1, 0x4e, 0x84, 0x30,
	0x10, 0x15, 0x04, 0x2a, 0x73, 0x9c, 0x18, 0xd3, 0xe8, 0x05, 0x7b, 0xe2, 0x54, 0x13, 0xf5, 0x33,
	0x24, 0x26, 0xc5, 0x93, 0x37, 0x85, 0x09, 0xcb, 0x81, 0xb6, 0xcb, 0xb0, 0xfb, 0xfd, 0x1b, 0x0a,
	0x64, 0x4f, 0xec, 0xe9, 0xf5, 0xbd, 0x4e, 0xde, 0xbc, 0x37, 0xf0, 0xe2, 0x47, 0x37, 0xb9, 0x37,
	0x26, 0xdb, 0xd6, 0x55, 0xbd, 0xa1, 0x0e, 0x2a, 0xca, 0xce, 0xe9, 0xa1, 0x6f, 0x46, 0xa7, 0x99,
	0xc6, 0x73, 0xdf, 0x90, 0x5e, 0xff, 0x55, 0x0e, 0xa2, 0x22, 0xe6, 0xbf, 0x8e, 0x14, 0x81, 0x30,
	0x74, 0x3c, 0x11, 0x4f, 0xf8, 0x08, 0xa9, 0x3f, 0x38, 0x4b, 0x32, 0x2a, 0xa2, 0x32, 0x37, 0x0b,
	0xc1, 0x27, 0xc8, 0x06, 0xee, 0x7e, 0x06, 0x2f, 0xe3, 0x20, 0xaf, 0x0c, 0x11, 0x92, 0xc6, 0xb5,
	0x24, 0xef, 0x8b, 0xa8, 0x4c, 0x4d, 0x78, 0xa3, 0x04, 0x31, 0xe3, 0x17, 0x59, 0x99, 0x04, 0x79,
	0xa3, 0xea, 0x13, 0x1e, 0x0c, 0xb1, 0x77, 0x96, 0x69, 0x67, 0xcf, 0xe6, 0x17, 0x5f, 0xfd, 0xde,
	0x7f, 0x41, 0xd4, 0x4b, 0x64, 0xfc, 0x86, 0x64, 0x4e, 0x8f, 0xaf, 0x7a, 0xaf, 0x95, 0x5e, 0x7b,
	0x3c, 0xab, 0x5b, 0x23, 0x4b, 0x06, 0x75, 0xf7, 0x9f, 0x85, 0x23, 0x7d, 0x5c, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x81, 0xee, 0x57, 0x6d, 0x43, 0x01, 0x00, 0x00,
}
