// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/getCaptcha/getCaptcha.proto

package go_micro_service_getCaptcha

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for GetCaptcha service

func NewGetCaptchaEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for GetCaptcha service

type GetCaptchaService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (GetCaptcha_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (GetCaptcha_PingPongService, error)
}

type getCaptchaService struct {
	c    client.Client
	name string
}

func NewGetCaptchaService(name string, c client.Client) GetCaptchaService {
	return &getCaptchaService{
		c:    c,
		name: name,
	}
}

func (c *getCaptchaService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "GetCaptcha.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *getCaptchaService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (GetCaptcha_StreamService, error) {
	req := c.c.NewRequest(c.name, "GetCaptcha.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &getCaptchaServiceStream{stream}, nil
}

type GetCaptcha_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type getCaptchaServiceStream struct {
	stream client.Stream
}

func (x *getCaptchaServiceStream) Close() error {
	return x.stream.Close()
}

func (x *getCaptchaServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *getCaptchaServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *getCaptchaServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *getCaptchaServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *getCaptchaService) PingPong(ctx context.Context, opts ...client.CallOption) (GetCaptcha_PingPongService, error) {
	req := c.c.NewRequest(c.name, "GetCaptcha.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &getCaptchaServicePingPong{stream}, nil
}

type GetCaptcha_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type getCaptchaServicePingPong struct {
	stream client.Stream
}

func (x *getCaptchaServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *getCaptchaServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *getCaptchaServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *getCaptchaServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *getCaptchaServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *getCaptchaServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for GetCaptcha service

type GetCaptchaHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, GetCaptcha_StreamStream) error
	PingPong(context.Context, GetCaptcha_PingPongStream) error
}

func RegisterGetCaptchaHandler(s server.Server, hdlr GetCaptchaHandler, opts ...server.HandlerOption) error {
	type getCaptcha interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type GetCaptcha struct {
		getCaptcha
	}
	h := &getCaptchaHandler{hdlr}
	return s.Handle(s.NewHandler(&GetCaptcha{h}, opts...))
}

type getCaptchaHandler struct {
	GetCaptchaHandler
}

func (h *getCaptchaHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.GetCaptchaHandler.Call(ctx, in, out)
}

func (h *getCaptchaHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.GetCaptchaHandler.Stream(ctx, m, &getCaptchaStreamStream{stream})
}

type GetCaptcha_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type getCaptchaStreamStream struct {
	stream server.Stream
}

func (x *getCaptchaStreamStream) Close() error {
	return x.stream.Close()
}

func (x *getCaptchaStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *getCaptchaStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *getCaptchaStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *getCaptchaStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *getCaptchaHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.GetCaptchaHandler.PingPong(ctx, &getCaptchaPingPongStream{stream})
}

type GetCaptcha_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type getCaptchaPingPongStream struct {
	stream server.Stream
}

func (x *getCaptchaPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *getCaptchaPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *getCaptchaPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *getCaptchaPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *getCaptchaPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *getCaptchaPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
