// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/checkCaptcha/checkCaptcha.proto

package go_micro_service_checkCaptcha

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EheckStatus int32

const (
	EheckStatus_Fail   EheckStatus = 0
	EheckStatus_Succ   EheckStatus = 1
	EheckStatus_Expire EheckStatus = 2
)

var EheckStatus_name = map[int32]string{
	0: "Fail",
	1: "Succ",
	2: "Expire",
}

var EheckStatus_value = map[string]int32{
	"Fail":   0,
	"Succ":   1,
	"Expire": 2,
}

func (x EheckStatus) String() string {
	return proto.EnumName(EheckStatus_name, int32(x))
}

func (EheckStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c197bcdc4cda2495, []int{0}
}

type Message struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_c197bcdc4cda2495, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

type Request struct {
	Number               string   `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Uuid                 string   `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_c197bcdc4cda2495, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *Request) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type Response struct {
	Status               EheckStatus `protobuf:"varint,1,opt,name=status,proto3,enum=go.micro.service.checkCaptcha.EheckStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_c197bcdc4cda2495, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatus() EheckStatus {
	if m != nil {
		return m.Status
	}
	return EheckStatus_Fail
}

func init() {
	proto.RegisterEnum("go.micro.service.checkCaptcha.EheckStatus", EheckStatus_name, EheckStatus_value)
	proto.RegisterType((*Message)(nil), "go.micro.service.checkCaptcha.Message")
	proto.RegisterType((*Request)(nil), "go.micro.service.checkCaptcha.Request")
	proto.RegisterType((*Response)(nil), "go.micro.service.checkCaptcha.Response")
}

func init() {
	proto.RegisterFile("proto/checkCaptcha/checkCaptcha.proto", fileDescriptor_c197bcdc4cda2495)
}

var fileDescriptor_c197bcdc4cda2495 = []byte{
	// 232 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0x4f, 0x4b, 0x03, 0x31,
	0x10, 0xc5, 0xbb, 0xa5, 0xa6, 0xed, 0x28, 0xb2, 0xcc, 0x41, 0x8a, 0x20, 0x48, 0xc0, 0x3f, 0x14,
	0x8c, 0x50, 0xf1, 0x0b, 0x58, 0xea, 0x4d, 0x0f, 0xe9, 0xcd, 0x5b, 0x1a, 0x87, 0x36, 0x6a, 0x9b,
	0x98, 0x49, 0xc4, 0x8f, 0x2f, 0x8d, 0x7b, 0x58, 0x2f, 0xee, 0x6d, 0x7e, 0x93, 0xf7, 0xf2, 0x78,
	0x03, 0x17, 0x21, 0xfa, 0xe4, 0x6f, 0xed, 0x86, 0xec, 0xfb, 0xdc, 0x84, 0x64, 0x37, 0xe6, 0x0f,
	0xa8, 0xf2, 0x8e, 0x67, 0x6b, 0xaf, 0xb6, 0xce, 0x46, 0xaf, 0x98, 0xe2, 0x97, 0xb3, 0xa4, 0xda,
	0x22, 0x39, 0x86, 0xe1, 0x13, 0x31, 0x9b, 0x35, 0xc9, 0x7b, 0x18, 0x6a, 0xfa, 0xcc, 0xc4, 0x09,
	0x4f, 0x40, 0xec, 0xf2, 0x76, 0x45, 0x71, 0x52, 0x9d, 0x57, 0xd7, 0x63, 0xdd, 0x10, 0x22, 0x0c,
	0x72, 0x76, 0xaf, 0x93, 0x7e, 0xd9, 0x96, 0x59, 0x3e, 0xc3, 0x48, 0x13, 0x07, 0xbf, 0x63, 0xc2,
	0x07, 0x10, 0x9c, 0x4c, 0xca, 0x5c, 0x7c, 0xc7, 0xb3, 0xa9, 0xfa, 0x37, 0x5d, 0x2d, 0xf6, 0xb0,
	0x2c, 0x0e, 0xdd, 0x38, 0xa7, 0x37, 0x70, 0xd8, 0x5a, 0xe3, 0x08, 0x06, 0x8f, 0xc6, 0x7d, 0xd4,
	0xbd, 0xfd, 0xb4, 0xcc, 0xd6, 0xd6, 0x15, 0x02, 0x88, 0xc5, 0x77, 0x70, 0x91, 0xea, 0xfe, 0xec,
	0x0d, 0x8e, 0xe6, 0xad, 0x2f, 0xf1, 0x05, 0x0e, 0x0a, 0xe3, 0x65, 0x47, 0x76, 0xd3, 0xf5, 0xf4,
	0xaa, 0x53, 0xf7, 0x5b, 0x4e, 0xf6, 0x56, 0xa2, 0x9c, 0xf4, 0xee, 0x27, 0x00, 0x00, 0xff, 0xff,
	0x8b, 0x0f, 0xbd, 0x8c, 0x7b, 0x01, 0x00, 0x00,
}
