// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/checkCaptcha/checkCaptcha.proto

package go_micro_service_checkCaptcha

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for CheckCaptcha service

func NewCheckCaptchaEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for CheckCaptcha service

type CheckCaptchaService interface {
	Check(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type checkCaptchaService struct {
	c    client.Client
	name string
}

func NewCheckCaptchaService(name string, c client.Client) CheckCaptchaService {
	return &checkCaptchaService{
		c:    c,
		name: name,
	}
}

func (c *checkCaptchaService) Check(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "CheckCaptcha.Check", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CheckCaptcha service

type CheckCaptchaHandler interface {
	Check(context.Context, *Request, *Response) error
}

func RegisterCheckCaptchaHandler(s server.Server, hdlr CheckCaptchaHandler, opts ...server.HandlerOption) error {
	type checkCaptcha interface {
		Check(ctx context.Context, in *Request, out *Response) error
	}
	type CheckCaptcha struct {
		checkCaptcha
	}
	h := &checkCaptchaHandler{hdlr}
	return s.Handle(s.NewHandler(&CheckCaptcha{h}, opts...))
}

type checkCaptchaHandler struct {
	CheckCaptchaHandler
}

func (h *checkCaptchaHandler) Check(ctx context.Context, in *Request, out *Response) error {
	return h.CheckCaptchaHandler.Check(ctx, in, out)
}
