// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/house/house.proto

package go_micro_service_house

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListRequest struct {
	Aid                  uint32   `protobuf:"varint,1,opt,name=aid,proto3" json:"aid,omitempty"`
	StartDate            string   `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate              string   `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Page                 uint32   `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc2bc500116e1060, []int{0}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetAid() uint32 {
	if m != nil {
		return m.Aid
	}
	return 0
}

func (m *ListRequest) GetStartDate() string {
	if m != nil {
		return m.StartDate
	}
	return ""
}

func (m *ListRequest) GetEndDate() string {
	if m != nil {
		return m.EndDate
	}
	return ""
}

func (m *ListRequest) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

type ListItem struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	AreaName             string   `protobuf:"bytes,2,opt,name=area_name,json=areaName,proto3" json:"area_name,omitempty"`
	Ctime                string   `protobuf:"bytes,3,opt,name=ctime,proto3" json:"ctime,omitempty"`
	HouseId              uint32   `protobuf:"varint,4,opt,name=house_id,json=houseId,proto3" json:"house_id,omitempty"`
	ImageUrl             string   `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	OrderCount           uint32   `protobuf:"varint,6,opt,name=order_count,json=orderCount,proto3" json:"order_count,omitempty"`
	Price                uint32   `protobuf:"varint,7,opt,name=price,proto3" json:"price,omitempty"`
	RoomCount            uint32   `protobuf:"varint,8,opt,name=room_count,json=roomCount,proto3" json:"room_count,omitempty"`
	Title                string   `protobuf:"bytes,9,opt,name=title,proto3" json:"title,omitempty"`
	UserAvatar           string   `protobuf:"bytes,10,opt,name=user_avatar,json=userAvatar,proto3" json:"user_avatar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListItem) Reset()         { *m = ListItem{} }
func (m *ListItem) String() string { return proto.CompactTextString(m) }
func (*ListItem) ProtoMessage()    {}
func (*ListItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc2bc500116e1060, []int{1}
}

func (m *ListItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListItem.Unmarshal(m, b)
}
func (m *ListItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListItem.Marshal(b, m, deterministic)
}
func (m *ListItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListItem.Merge(m, src)
}
func (m *ListItem) XXX_Size() int {
	return xxx_messageInfo_ListItem.Size(m)
}
func (m *ListItem) XXX_DiscardUnknown() {
	xxx_messageInfo_ListItem.DiscardUnknown(m)
}

var xxx_messageInfo_ListItem proto.InternalMessageInfo

func (m *ListItem) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ListItem) GetAreaName() string {
	if m != nil {
		return m.AreaName
	}
	return ""
}

func (m *ListItem) GetCtime() string {
	if m != nil {
		return m.Ctime
	}
	return ""
}

func (m *ListItem) GetHouseId() uint32 {
	if m != nil {
		return m.HouseId
	}
	return 0
}

func (m *ListItem) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

func (m *ListItem) GetOrderCount() uint32 {
	if m != nil {
		return m.OrderCount
	}
	return 0
}

func (m *ListItem) GetPrice() uint32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *ListItem) GetRoomCount() uint32 {
	if m != nil {
		return m.RoomCount
	}
	return 0
}

func (m *ListItem) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ListItem) GetUserAvatar() string {
	if m != nil {
		return m.UserAvatar
	}
	return ""
}

type ListResponse struct {
	CurrentPage          uint32      `protobuf:"varint,1,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	Houses               []*ListItem `protobuf:"bytes,2,rep,name=houses,proto3" json:"houses,omitempty"`
	TotalPage            uint32      `protobuf:"varint,3,opt,name=total_page,json=totalPage,proto3" json:"total_page,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc2bc500116e1060, []int{2}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetCurrentPage() uint32 {
	if m != nil {
		return m.CurrentPage
	}
	return 0
}

func (m *ListResponse) GetHouses() []*ListItem {
	if m != nil {
		return m.Houses
	}
	return nil
}

func (m *ListResponse) GetTotalPage() uint32 {
	if m != nil {
		return m.TotalPage
	}
	return 0
}

type CreateRequest struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Price                uint32   `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	AreaId               uint32   `protobuf:"varint,3,opt,name=area_id,json=areaId,proto3" json:"area_id,omitempty"`
	Address              string   `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	RoomCount            uint32   `protobuf:"varint,5,opt,name=room_count,json=roomCount,proto3" json:"room_count,omitempty"`
	Acreage              uint32   `protobuf:"varint,6,opt,name=acreage,proto3" json:"acreage,omitempty"`
	Unit                 string   `protobuf:"bytes,7,opt,name=unit,proto3" json:"unit,omitempty"`
	Capacity             uint32   `protobuf:"varint,8,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Beds                 string   `protobuf:"bytes,9,opt,name=beds,proto3" json:"beds,omitempty"`
	Deposit              uint32   `protobuf:"varint,10,opt,name=deposit,proto3" json:"deposit,omitempty"`
	MinDays              uint32   `protobuf:"varint,11,opt,name=min_days,json=minDays,proto3" json:"min_days,omitempty"`
	MaxDays              uint32   `protobuf:"varint,12,opt,name=max_days,json=maxDays,proto3" json:"max_days,omitempty"`
	Facility             []byte   `protobuf:"bytes,13,opt,name=facility,proto3" json:"facility,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc2bc500116e1060, []int{3}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreateRequest) GetPrice() uint32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *CreateRequest) GetAreaId() uint32 {
	if m != nil {
		return m.AreaId
	}
	return 0
}

func (m *CreateRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *CreateRequest) GetRoomCount() uint32 {
	if m != nil {
		return m.RoomCount
	}
	return 0
}

func (m *CreateRequest) GetAcreage() uint32 {
	if m != nil {
		return m.Acreage
	}
	return 0
}

func (m *CreateRequest) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *CreateRequest) GetCapacity() uint32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *CreateRequest) GetBeds() string {
	if m != nil {
		return m.Beds
	}
	return ""
}

func (m *CreateRequest) GetDeposit() uint32 {
	if m != nil {
		return m.Deposit
	}
	return 0
}

func (m *CreateRequest) GetMinDays() uint32 {
	if m != nil {
		return m.MinDays
	}
	return 0
}

func (m *CreateRequest) GetMaxDays() uint32 {
	if m != nil {
		return m.MaxDays
	}
	return 0
}

func (m *CreateRequest) GetFacility() []byte {
	if m != nil {
		return m.Facility
	}
	return nil
}

type CreateResponse struct {
	HouseId              uint32   `protobuf:"varint,1,opt,name=house_id,json=houseId,proto3" json:"house_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc2bc500116e1060, []int{4}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetHouseId() uint32 {
	if m != nil {
		return m.HouseId
	}
	return 0
}

type UploadImageRequest struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadImageRequest) Reset()         { *m = UploadImageRequest{} }
func (m *UploadImageRequest) String() string { return proto.CompactTextString(m) }
func (*UploadImageRequest) ProtoMessage()    {}
func (*UploadImageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc2bc500116e1060, []int{5}
}

func (m *UploadImageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadImageRequest.Unmarshal(m, b)
}
func (m *UploadImageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadImageRequest.Marshal(b, m, deterministic)
}
func (m *UploadImageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadImageRequest.Merge(m, src)
}
func (m *UploadImageRequest) XXX_Size() int {
	return xxx_messageInfo_UploadImageRequest.Size(m)
}
func (m *UploadImageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadImageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadImageRequest proto.InternalMessageInfo

func (m *UploadImageRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type UploadImageResponse struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadImageResponse) Reset()         { *m = UploadImageResponse{} }
func (m *UploadImageResponse) String() string { return proto.CompactTextString(m) }
func (*UploadImageResponse) ProtoMessage()    {}
func (*UploadImageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc2bc500116e1060, []int{6}
}

func (m *UploadImageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadImageResponse.Unmarshal(m, b)
}
func (m *UploadImageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadImageResponse.Marshal(b, m, deterministic)
}
func (m *UploadImageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadImageResponse.Merge(m, src)
}
func (m *UploadImageResponse) XXX_Size() int {
	return xxx_messageInfo_UploadImageResponse.Size(m)
}
func (m *UploadImageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadImageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UploadImageResponse proto.InternalMessageInfo

func (m *UploadImageResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type Comment struct {
	Comment              string   `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	Ctime                string   `protobuf:"bytes,2,opt,name=ctime,proto3" json:"ctime,omitempty"`
	UserName             string   `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Comment) Reset()         { *m = Comment{} }
func (m *Comment) String() string { return proto.CompactTextString(m) }
func (*Comment) ProtoMessage()    {}
func (*Comment) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc2bc500116e1060, []int{7}
}

func (m *Comment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Comment.Unmarshal(m, b)
}
func (m *Comment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Comment.Marshal(b, m, deterministic)
}
func (m *Comment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Comment.Merge(m, src)
}
func (m *Comment) XXX_Size() int {
	return xxx_messageInfo_Comment.Size(m)
}
func (m *Comment) XXX_DiscardUnknown() {
	xxx_messageInfo_Comment.DiscardUnknown(m)
}

var xxx_messageInfo_Comment proto.InternalMessageInfo

func (m *Comment) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *Comment) GetCtime() string {
	if m != nil {
		return m.Ctime
	}
	return ""
}

func (m *Comment) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

type DetailRequest struct {
	HouseId              uint32   `protobuf:"bytes,1,opt,name=house_id,json=houseId,proto3" json:"house_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetailRequest) Reset()         { *m = DetailRequest{} }
func (m *DetailRequest) String() string { return proto.CompactTextString(m) }
func (*DetailRequest) ProtoMessage()    {}
func (*DetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc2bc500116e1060, []int{8}
}

func (m *DetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetailRequest.Unmarshal(m, b)
}
func (m *DetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetailRequest.Marshal(b, m, deterministic)
}
func (m *DetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetailRequest.Merge(m, src)
}
func (m *DetailRequest) XXX_Size() int {
	return xxx_messageInfo_DetailRequest.Size(m)
}
func (m *DetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DetailRequest proto.InternalMessageInfo

func (m *DetailRequest) GetHouseId() uint32 {
	if m != nil {
		return m.HouseId
	}
	return 0
}

type DetailResponse struct {
	Acreage              uint32     `protobuf:"varint,1,opt,name=acreage,proto3" json:"acreage,omitempty"`
	Address              string     `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Beds                 string     `protobuf:"bytes,3,opt,name=beds,proto3" json:"beds,omitempty"`
	Capacity             uint32     `protobuf:"varint,4,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Comments             []*Comment `protobuf:"bytes,5,rep,name=comments,proto3" json:"comments,omitempty"`
	Deposit              uint32     `protobuf:"varint,6,opt,name=deposit,proto3" json:"deposit,omitempty"`
	Facilities           []string   `protobuf:"bytes,7,opt,name=facilities,proto3" json:"facilities,omitempty"`
	Hid                  uint32     `protobuf:"varint,8,opt,name=hid,proto3" json:"hid,omitempty"`
	ImgUrls              []string   `protobuf:"bytes,9,opt,name=img_urls,json=imgUrls,proto3" json:"img_urls,omitempty"`
	MinDays              uint32     `protobuf:"varint,10,opt,name=min_days,json=minDays,proto3" json:"min_days,omitempty"`
	MaxDays              uint32     `protobuf:"varint,11,opt,name=max_days,json=maxDays,proto3" json:"max_days,omitempty"`
	Price                uint32     `protobuf:"varint,12,opt,name=price,proto3" json:"price,omitempty"`
	RoomCount            uint32     `protobuf:"varint,13,opt,name=room_count,json=roomCount,proto3" json:"room_count,omitempty"`
	Title                string     `protobuf:"bytes,14,opt,name=title,proto3" json:"title,omitempty"`
	Unit                 string     `protobuf:"bytes,15,opt,name=unit,proto3" json:"unit,omitempty"`
	UserAvatar           string     `protobuf:"bytes,16,opt,name=user_avatar,json=userAvatar,proto3" json:"user_avatar,omitempty"`
	UserId               uint32     `protobuf:"varint,17,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName             string     `protobuf:"bytes,18,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *DetailResponse) Reset()         { *m = DetailResponse{} }
func (m *DetailResponse) String() string { return proto.CompactTextString(m) }
func (*DetailResponse) ProtoMessage()    {}
func (*DetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc2bc500116e1060, []int{9}
}

func (m *DetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetailResponse.Unmarshal(m, b)
}
func (m *DetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetailResponse.Marshal(b, m, deterministic)
}
func (m *DetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetailResponse.Merge(m, src)
}
func (m *DetailResponse) XXX_Size() int {
	return xxx_messageInfo_DetailResponse.Size(m)
}
func (m *DetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DetailResponse proto.InternalMessageInfo

func (m *DetailResponse) GetAcreage() uint32 {
	if m != nil {
		return m.Acreage
	}
	return 0
}

func (m *DetailResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *DetailResponse) GetBeds() string {
	if m != nil {
		return m.Beds
	}
	return ""
}

func (m *DetailResponse) GetCapacity() uint32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *DetailResponse) GetComments() []*Comment {
	if m != nil {
		return m.Comments
	}
	return nil
}

func (m *DetailResponse) GetDeposit() uint32 {
	if m != nil {
		return m.Deposit
	}
	return 0
}

func (m *DetailResponse) GetFacilities() []byte {
	if m != nil {
		return m.Facilities
	}
	return nil
}

func (m *DetailResponse) GetHid() uint32 {
	if m != nil {
		return m.Hid
	}
	return 0
}

func (m *DetailResponse) GetImgUrls() []byte {
	if m != nil {
		return m.ImgUrls
	}
	return nil
}

func (m *DetailResponse) GetMinDays() uint32 {
	if m != nil {
		return m.MinDays
	}
	return 0
}

func (m *DetailResponse) GetMaxDays() uint32 {
	if m != nil {
		return m.MaxDays
	}
	return 0
}

func (m *DetailResponse) GetPrice() uint32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *DetailResponse) GetRoomCount() uint32 {
	if m != nil {
		return m.RoomCount
	}
	return 0
}

func (m *DetailResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *DetailResponse) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *DetailResponse) GetUserAvatar() string {
	if m != nil {
		return m.UserAvatar
	}
	return ""
}

func (m *DetailResponse) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *DetailResponse) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func init() {
	proto.RegisterType((*ListRequest)(nil), "go.micro.service.house.ListRequest")
	proto.RegisterType((*ListItem)(nil), "go.micro.service.house.ListItem")
	proto.RegisterType((*ListResponse)(nil), "go.micro.service.house.ListResponse")
	proto.RegisterType((*CreateRequest)(nil), "go.micro.service.house.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "go.micro.service.house.CreateResponse")
	proto.RegisterType((*UploadImageRequest)(nil), "go.micro.service.house.UploadImageRequest")
	proto.RegisterType((*UploadImageResponse)(nil), "go.micro.service.house.UploadImageResponse")
	proto.RegisterType((*Comment)(nil), "go.micro.service.house.Comment")
	proto.RegisterType((*DetailRequest)(nil), "go.micro.service.house.DetailRequest")
	proto.RegisterType((*DetailResponse)(nil), "go.micro.service.house.DetailResponse")
}

func init() { proto.RegisterFile("proto/house/house.proto", fileDescriptor_fc2bc500116e1060) }

var fileDescriptor_fc2bc500116e1060 = []byte{
	// 832 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0xcd, 0x8e, 0x1b, 0x45,
	0x10, 0x8e, 0xff, 0x67, 0xca, 0xf6, 0x12, 0x1a, 0x44, 0x06, 0x47, 0x10, 0x33, 0x40, 0x58, 0x25,
	0x92, 0x91, 0xc2, 0x05, 0x89, 0x13, 0xda, 0x3d, 0x60, 0x09, 0x21, 0x34, 0x68, 0x91, 0x38, 0x8d,
	0x3a, 0xd3, 0x8d, 0xb7, 0xa5, 0xf9, 0x31, 0xdd, 0xed, 0x28, 0x7b, 0xe7, 0xc4, 0x33, 0xf0, 0x5e,
	0xbc, 0x0c, 0x07, 0x54, 0xd5, 0x3d, 0xb3, 0x3d, 0x0e, 0x13, 0xb8, 0x58, 0x5d, 0x3f, 0x5d, 0x3d,
	0x55, 0xdf, 0xf7, 0x95, 0x0c, 0x8f, 0x8e, 0xba, 0xb1, 0xcd, 0x97, 0xb7, 0xcd, 0xc9, 0x48, 0xf7,
	0xbb, 0x23, 0x0f, 0xfb, 0xe0, 0xd0, 0xec, 0x2a, 0x55, 0xe8, 0x66, 0x67, 0xa4, 0x7e, 0xa5, 0x0a,
	0xb9, 0xa3, 0x68, 0x5a, 0xc1, 0xf2, 0x7b, 0x65, 0x6c, 0x26, 0x7f, 0x3b, 0x49, 0x63, 0xd9, 0x43,
	0x98, 0x70, 0x25, 0x92, 0xd1, 0x76, 0x74, 0xb9, 0xce, 0xf0, 0xc8, 0x3e, 0x02, 0x30, 0x96, 0x6b,
	0x9b, 0x0b, 0x6e, 0x65, 0x32, 0xde, 0x8e, 0x2e, 0xe3, 0x2c, 0x26, 0xcf, 0x35, 0xb7, 0x92, 0x7d,
	0x08, 0x91, 0xac, 0x85, 0x0b, 0x4e, 0x28, 0xb8, 0x90, 0xb5, 0xa0, 0x10, 0x83, 0xe9, 0x91, 0x1f,
	0x64, 0x32, 0xa5, 0x62, 0x74, 0x4e, 0xff, 0x1c, 0x43, 0x84, 0xef, 0xed, 0xad, 0xac, 0x58, 0x02,
	0x0b, 0x2e, 0x84, 0x96, 0xc6, 0xd0, 0x83, 0x71, 0xd6, 0x9a, 0xec, 0x31, 0xc4, 0x5c, 0x4b, 0x9e,
	0xd7, 0xbc, 0x6a, 0xdf, 0x8c, 0xd0, 0xf1, 0x03, 0xaf, 0x24, 0x7b, 0x1f, 0x66, 0x85, 0x55, 0x55,
	0xfb, 0x9e, 0x33, 0xf0, 0x43, 0xa8, 0xa3, 0x5c, 0x09, 0xff, 0xe2, 0x82, 0xec, 0xbd, 0xc0, 0x6a,
	0xaa, 0xe2, 0x07, 0x99, 0x9f, 0x74, 0x99, 0xcc, 0x5c, 0x35, 0x72, 0xdc, 0xe8, 0x92, 0x3d, 0x81,
	0x65, 0xa3, 0x85, 0xd4, 0x79, 0xd1, 0x9c, 0x6a, 0x9b, 0xcc, 0xe9, 0x2a, 0x90, 0xeb, 0x0a, 0x3d,
	0xf8, 0xdc, 0x51, 0xab, 0x42, 0x26, 0x0b, 0x0a, 0x39, 0x03, 0xc7, 0xa2, 0x9b, 0xa6, 0xf2, 0xb7,
	0x22, 0x0a, 0xc5, 0xe8, 0xe9, 0x2e, 0x59, 0x65, 0x4b, 0x99, 0xc4, 0xee, 0x1b, 0xc9, 0xc0, 0xb7,
	0x4e, 0x46, 0xea, 0x9c, 0xbf, 0xe2, 0x96, 0xeb, 0x04, 0x28, 0x06, 0xe8, 0xfa, 0x96, 0x3c, 0xe9,
	0x1f, 0x23, 0x58, 0x39, 0x38, 0xcc, 0xb1, 0xa9, 0x8d, 0x64, 0x9f, 0xc0, 0xaa, 0x38, 0x69, 0x2d,
	0x6b, 0x9b, 0xd3, 0x2c, 0x1d, 0x30, 0x4b, 0xef, 0xfb, 0x91, 0x1f, 0x24, 0xfb, 0x1a, 0xe6, 0xd4,
	0xa8, 0x49, 0xc6, 0xdb, 0xc9, 0xe5, 0xf2, 0xc5, 0x76, 0xf7, 0xef, 0x50, 0xef, 0xda, 0xb9, 0x67,
	0x3e, 0x1f, 0x7b, 0xb0, 0x8d, 0xe5, 0xa5, 0x2b, 0x3d, 0x71, 0x3d, 0x90, 0x07, 0x0b, 0xa7, 0x7f,
	0x8d, 0x61, 0x7d, 0xa5, 0x25, 0xb7, 0xb2, 0x65, 0x47, 0xd7, 0xd5, 0x28, 0xec, 0xaa, 0x1b, 0xd0,
	0x38, 0x1c, 0xd0, 0x23, 0x58, 0x10, 0x84, 0x4a, 0xf8, 0xca, 0x73, 0x34, 0xf7, 0x22, 0x44, 0x7d,
	0xda, 0x47, 0xbd, 0x3f, 0xd3, 0xd9, 0xf9, 0x4c, 0xf1, 0x62, 0xa1, 0x25, 0x7e, 0xab, 0x43, 0xa9,
	0x35, 0x91, 0x69, 0xa7, 0x5a, 0x59, 0x42, 0x28, 0xce, 0xe8, 0xcc, 0x36, 0x10, 0x15, 0xfc, 0xc8,
	0x0b, 0x65, 0xef, 0x3c, 0x3c, 0x9d, 0x8d, 0xf9, 0x2f, 0xa5, 0x30, 0x1e, 0x1c, 0x3a, 0x63, 0x75,
	0x21, 0x8f, 0x8d, 0x51, 0x96, 0x70, 0x59, 0x67, 0xad, 0x89, 0xcc, 0xaa, 0x54, 0x9d, 0x0b, 0x7e,
	0x67, 0x92, 0xa5, 0x0b, 0x55, 0xaa, 0xbe, 0xe6, 0x77, 0x86, 0x42, 0xfc, 0xb5, 0x0b, 0xad, 0x7c,
	0x88, 0xbf, 0xa6, 0xd0, 0x06, 0xa2, 0x5f, 0x79, 0xa1, 0x4a, 0x7c, 0x7f, 0xbd, 0x1d, 0x5d, 0xae,
	0xb2, 0xce, 0x4e, 0x9f, 0xc3, 0x45, 0x3b, 0x58, 0x8f, 0x73, 0xc8, 0xde, 0x51, 0x8f, 0xbd, 0xe9,
	0x53, 0x60, 0x37, 0xc7, 0xb2, 0xe1, 0x62, 0x8f, 0x94, 0x0d, 0x84, 0x8a, 0x6c, 0x76, 0x40, 0xe0,
	0x31, 0xfd, 0x02, 0xde, 0xeb, 0xe5, 0xf9, 0xca, 0x6f, 0x26, 0xfe, 0x0c, 0x8b, 0xab, 0xa6, 0xaa,
	0xa4, 0x1b, 0x69, 0xe1, 0x8e, 0xad, 0x02, 0xbd, 0x79, 0x2f, 0xb2, 0x71, 0x28, 0xb2, 0xc7, 0x10,
	0x13, 0x81, 0x49, 0x97, 0x4e, 0x7e, 0x11, 0x3a, 0x50, 0x97, 0xe9, 0x33, 0x58, 0x5f, 0x4b, 0xcb,
	0x55, 0xd9, 0x7e, 0xe3, 0x79, 0x53, 0xf1, 0x7d, 0x53, 0xbf, 0x4f, 0xe1, 0xa2, 0x4d, 0xf6, 0x1f,
	0x1a, 0xc0, 0x3b, 0xea, 0xc3, 0x1b, 0x30, 0x66, 0xdc, 0x67, 0x4c, 0x0b, 0xe4, 0x24, 0x00, 0x32,
	0x04, 0x7e, 0x7a, 0x06, 0xfc, 0x37, 0x10, 0xf9, 0x06, 0x4d, 0x32, 0x23, 0xb5, 0x3c, 0x19, 0x52,
	0x8b, 0x1f, 0x51, 0xd6, 0x5d, 0x08, 0x19, 0x32, 0xef, 0x33, 0xe4, 0x63, 0x00, 0x8f, 0xad, 0x92,
	0x86, 0x58, 0xb8, 0xca, 0x02, 0x0f, 0x62, 0x70, 0xab, 0x84, 0xa7, 0x21, 0x1e, 0x71, 0x34, 0xaa,
	0x3a, 0xe0, 0x42, 0x72, 0x2c, 0x5c, 0x65, 0x0b, 0x55, 0x1d, 0x6e, 0x74, 0x69, 0x7a, 0x74, 0x83,
	0x61, 0xba, 0x2d, 0xfb, 0x74, 0xeb, 0x44, 0xb8, 0x1a, 0xde, 0x52, 0xeb, 0xc1, 0x2d, 0x75, 0x11,
	0xea, 0xb9, 0x55, 0xd3, 0x3b, 0x81, 0x9a, 0xce, 0x36, 0xd7, 0xc3, 0xf3, 0xcd, 0x85, 0x72, 0xa7,
	0x04, 0x25, 0x92, 0x77, 0x9d, 0xdc, 0xd1, 0x74, 0xcb, 0xf7, 0x9e, 0x32, 0xac, 0x4f, 0x99, 0x17,
	0x7f, 0x8f, 0x61, 0xf6, 0x1d, 0x8e, 0x9b, 0xfd, 0x04, 0x53, 0xdc, 0x4f, 0xec, 0xd3, 0xb7, 0x6d,
	0x2f, 0x4f, 0xac, 0xcd, 0x67, 0x6f, 0x4f, 0x72, 0x84, 0x4a, 0x1f, 0xb0, 0x5f, 0x60, 0xee, 0x74,
	0xc6, 0x3e, 0x1f, 0x84, 0x39, 0x5c, 0x70, 0x9b, 0xa7, 0xff, 0x95, 0xd6, 0x95, 0xbe, 0x85, 0x65,
	0xa0, 0x36, 0xf6, 0x6c, 0xe8, 0xe2, 0x9b, 0xd2, 0xdd, 0x3c, 0xff, 0x5f, 0xb9, 0x61, 0x13, 0x4e,
	0x29, 0xc3, 0x4d, 0xf4, 0x64, 0x37, 0xdc, 0x44, 0x5f, 0x70, 0xe9, 0x83, 0x97, 0x73, 0xfa, 0x6f,
	0xf0, 0xd5, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb9, 0xd4, 0xc5, 0x6b, 0x36, 0x08, 0x00, 0x00,
}
