// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/user/user.proto

package go_micro_service_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for User service

func NewUserEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for User service

type UserService interface {
	Info(ctx context.Context, in *InfoRequest, opts ...client.CallOption) (*InfoResponse, error)
	UploadAvatar(ctx context.Context, in *AvatarRequest, opts ...client.CallOption) (*AvatarResponse, error)
	UpdateName(ctx context.Context, in *UpNameRequest, opts ...client.CallOption) (*UpNameResponse, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) Info(ctx context.Context, in *InfoRequest, opts ...client.CallOption) (*InfoResponse, error) {
	req := c.c.NewRequest(c.name, "User.Info", in)
	out := new(InfoResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) UploadAvatar(ctx context.Context, in *AvatarRequest, opts ...client.CallOption) (*AvatarResponse, error) {
	req := c.c.NewRequest(c.name, "User.UploadAvatar", in)
	out := new(AvatarResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) UpdateName(ctx context.Context, in *UpNameRequest, opts ...client.CallOption) (*UpNameResponse, error) {
	req := c.c.NewRequest(c.name, "User.UpdateName", in)
	out := new(UpNameResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for User service

type UserHandler interface {
	Info(context.Context, *InfoRequest, *InfoResponse) error
	UploadAvatar(context.Context, *AvatarRequest, *AvatarResponse) error
	UpdateName(context.Context, *UpNameRequest, *UpNameResponse) error
}

func RegisterUserHandler(s server.Server, hdlr UserHandler, opts ...server.HandlerOption) error {
	type user interface {
		Info(ctx context.Context, in *InfoRequest, out *InfoResponse) error
		UploadAvatar(ctx context.Context, in *AvatarRequest, out *AvatarResponse) error
		UpdateName(ctx context.Context, in *UpNameRequest, out *UpNameResponse) error
	}
	type User struct {
		user
	}
	h := &userHandler{hdlr}
	return s.Handle(s.NewHandler(&User{h}, opts...))
}

type userHandler struct {
	UserHandler
}

func (h *userHandler) Info(ctx context.Context, in *InfoRequest, out *InfoResponse) error {
	return h.UserHandler.Info(ctx, in, out)
}

func (h *userHandler) UploadAvatar(ctx context.Context, in *AvatarRequest, out *AvatarResponse) error {
	return h.UserHandler.UploadAvatar(ctx, in, out)
}

func (h *userHandler) UpdateName(ctx context.Context, in *UpNameRequest, out *UpNameResponse) error {
	return h.UserHandler.UpdateName(ctx, in, out)
}
