// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/auth/auth.proto

package go_micro_service_auth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Auth service

func NewAuthEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Auth service

type AuthService interface {
	CheckRealNameAuth(ctx context.Context, in *CheckAuthRequest, opts ...client.CallOption) (*CheckAuthResponse, error)
	RealNameAuth(ctx context.Context, in *AuthRequest, opts ...client.CallOption) (*AuthRequest, error)
}

type authService struct {
	c    client.Client
	name string
}

func NewAuthService(name string, c client.Client) AuthService {
	return &authService{
		c:    c,
		name: name,
	}
}

func (c *authService) CheckRealNameAuth(ctx context.Context, in *CheckAuthRequest, opts ...client.CallOption) (*CheckAuthResponse, error) {
	req := c.c.NewRequest(c.name, "Auth.CheckRealNameAuth", in)
	out := new(CheckAuthResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authService) RealNameAuth(ctx context.Context, in *AuthRequest, opts ...client.CallOption) (*AuthRequest, error) {
	req := c.c.NewRequest(c.name, "Auth.RealNameAuth", in)
	out := new(AuthRequest)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Auth service

type AuthHandler interface {
	CheckRealNameAuth(context.Context, *CheckAuthRequest, *CheckAuthResponse) error
	RealNameAuth(context.Context, *AuthRequest, *AuthRequest) error
}

func RegisterAuthHandler(s server.Server, hdlr AuthHandler, opts ...server.HandlerOption) error {
	type auth interface {
		CheckRealNameAuth(ctx context.Context, in *CheckAuthRequest, out *CheckAuthResponse) error
		RealNameAuth(ctx context.Context, in *AuthRequest, out *AuthRequest) error
	}
	type Auth struct {
		auth
	}
	h := &authHandler{hdlr}
	return s.Handle(s.NewHandler(&Auth{h}, opts...))
}

type authHandler struct {
	AuthHandler
}

func (h *authHandler) CheckRealNameAuth(ctx context.Context, in *CheckAuthRequest, out *CheckAuthResponse) error {
	return h.AuthHandler.CheckRealNameAuth(ctx, in, out)
}

func (h *authHandler) RealNameAuth(ctx context.Context, in *AuthRequest, out *AuthRequest) error {
	return h.AuthHandler.RealNameAuth(ctx, in, out)
}
