// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/auth/auth.proto

package go_micro_service_auth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuthStatus int32

const (
	AuthStatus_AuthFail AuthStatus = 0
	AuthStatus_AuthSucc AuthStatus = 1
)

var AuthStatus_name = map[int32]string{
	0: "AuthFail",
	1: "AuthSucc",
}

var AuthStatus_value = map[string]int32{
	"AuthFail": 0,
	"AuthSucc": 1,
}

func (x AuthStatus) String() string {
	return proto.EnumName(AuthStatus_name, int32(x))
}

func (AuthStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{0}
}

type CheckAuthRequest struct {
	UserId               uint64   `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckAuthRequest) Reset()         { *m = CheckAuthRequest{} }
func (m *CheckAuthRequest) String() string { return proto.CompactTextString(m) }
func (*CheckAuthRequest) ProtoMessage()    {}
func (*CheckAuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{0}
}

func (m *CheckAuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckAuthRequest.Unmarshal(m, b)
}
func (m *CheckAuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckAuthRequest.Marshal(b, m, deterministic)
}
func (m *CheckAuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckAuthRequest.Merge(m, src)
}
func (m *CheckAuthRequest) XXX_Size() int {
	return xxx_messageInfo_CheckAuthRequest.Size(m)
}
func (m *CheckAuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckAuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckAuthRequest proto.InternalMessageInfo

func (m *CheckAuthRequest) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type CheckAuthResponse struct {
	UserId               uint64   `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Mobile               string   `protobuf:"bytes,3,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	RealName             string   `protobuf:"bytes,4,opt,name=RealName,proto3" json:"RealName,omitempty"`
	IdCard               string   `protobuf:"bytes,5,opt,name=IdCard,proto3" json:"IdCard,omitempty"`
	AvatarUrl            string   `protobuf:"bytes,6,opt,name=AvatarUrl,proto3" json:"AvatarUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckAuthResponse) Reset()         { *m = CheckAuthResponse{} }
func (m *CheckAuthResponse) String() string { return proto.CompactTextString(m) }
func (*CheckAuthResponse) ProtoMessage()    {}
func (*CheckAuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{1}
}

func (m *CheckAuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckAuthResponse.Unmarshal(m, b)
}
func (m *CheckAuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckAuthResponse.Marshal(b, m, deterministic)
}
func (m *CheckAuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckAuthResponse.Merge(m, src)
}
func (m *CheckAuthResponse) XXX_Size() int {
	return xxx_messageInfo_CheckAuthResponse.Size(m)
}
func (m *CheckAuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckAuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckAuthResponse proto.InternalMessageInfo

func (m *CheckAuthResponse) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CheckAuthResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CheckAuthResponse) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *CheckAuthResponse) GetRealName() string {
	if m != nil {
		return m.RealName
	}
	return ""
}

func (m *CheckAuthResponse) GetIdCard() string {
	if m != nil {
		return m.IdCard
	}
	return ""
}

func (m *CheckAuthResponse) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

type AuthRequest struct {
	UserId               uint64   `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	RealName             string   `protobuf:"bytes,2,opt,name=RealName,proto3" json:"RealName,omitempty"`
	IdCard               string   `protobuf:"bytes,3,opt,name=IdCard,proto3" json:"IdCard,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{2}
}

func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (m *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(m, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *AuthRequest) GetRealName() string {
	if m != nil {
		return m.RealName
	}
	return ""
}

func (m *AuthRequest) GetIdCard() string {
	if m != nil {
		return m.IdCard
	}
	return ""
}

type AuthResponse struct {
	Status               AuthStatus `protobuf:"varint,1,opt,name=Status,proto3,enum=go.micro.service.auth.AuthStatus" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{3}
}

func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (m *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(m, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

func (m *AuthResponse) GetStatus() AuthStatus {
	if m != nil {
		return m.Status
	}
	return AuthStatus_AuthFail
}

func init() {
	proto.RegisterEnum("go.micro.service.auth.AuthStatus", AuthStatus_name, AuthStatus_value)
	proto.RegisterType((*CheckAuthRequest)(nil), "go.micro.service.auth.CheckAuthRequest")
	proto.RegisterType((*CheckAuthResponse)(nil), "go.micro.service.auth.CheckAuthResponse")
	proto.RegisterType((*AuthRequest)(nil), "go.micro.service.auth.AuthRequest")
	proto.RegisterType((*AuthResponse)(nil), "go.micro.service.auth.AuthResponse")
}

func init() { proto.RegisterFile("proto/auth/auth.proto", fileDescriptor_82b5829f48cfb8e5) }

var fileDescriptor_82b5829f48cfb8e5 = []byte{
	// 313 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0x97, 0xad, 0x96, 0xed, 0x39, 0xa4, 0x06, 0x26, 0x65, 0x78, 0x98, 0xb9, 0x58, 0x76,
	0x88, 0x30, 0x4f, 0x1e, 0xc7, 0x40, 0xe8, 0x41, 0x0f, 0x1d, 0x03, 0x3d, 0x66, 0x6d, 0xb0, 0xc5,
	0xce, 0xcc, 0x24, 0xdd, 0x77, 0xf2, 0xab, 0xf8, 0xa9, 0x24, 0x69, 0xeb, 0x56, 0xb1, 0xba, 0x4b,
	0xe9, 0xef, 0xbd, 0xff, 0x3f, 0xff, 0xbe, 0xbc, 0xc2, 0x68, 0x2b, 0x85, 0x16, 0x37, 0xac, 0xd0,
	0xa9, 0x7d, 0x50, 0xcb, 0x78, 0xf4, 0x22, 0xe8, 0x26, 0x8b, 0xa5, 0xa0, 0x8a, 0xcb, 0x5d, 0x16,
	0x73, 0x6a, 0x9a, 0x64, 0x0a, 0xde, 0x22, 0xe5, 0xf1, 0xeb, 0xbc, 0xd0, 0x69, 0xc4, 0xdf, 0x0b,
	0xae, 0x34, 0xbe, 0x00, 0x77, 0xa5, 0xb8, 0x0c, 0x13, 0x1f, 0x4d, 0x50, 0xe0, 0x44, 0x15, 0x91,
	0x0f, 0x04, 0xe7, 0x07, 0x62, 0xb5, 0x15, 0x6f, 0x8a, 0xb7, 0xa9, 0x31, 0x06, 0xe7, 0x91, 0x6d,
	0xb8, 0xdf, 0x9d, 0xa0, 0x60, 0x10, 0xd9, 0x77, 0xa3, 0x7d, 0x10, 0xeb, 0x2c, 0xe7, 0x7e, 0xcf,
	0x56, 0x2b, 0xc2, 0x63, 0xe8, 0x47, 0x9c, 0xe5, 0x56, 0xef, 0xd8, 0xce, 0x37, 0x1b, 0x4f, 0x98,
	0x2c, 0x98, 0x4c, 0xfc, 0x93, 0xd2, 0x53, 0x12, 0xbe, 0x84, 0xc1, 0x7c, 0xc7, 0x34, 0x93, 0x2b,
	0x99, 0xfb, 0xae, 0x6d, 0xed, 0x0b, 0xe4, 0x19, 0x4e, 0x8f, 0x18, 0xa9, 0x11, 0xdc, 0x6d, 0x0d,
	0xee, 0x1d, 0x06, 0x93, 0x10, 0x86, 0x8d, 0x0b, 0xb8, 0x03, 0x77, 0xa9, 0x99, 0x2e, 0x94, 0x3d,
	0xfb, 0x6c, 0x76, 0x45, 0x7f, 0xbd, 0x6a, 0x6a, 0x4c, 0xa5, 0x30, 0xaa, 0x0c, 0xd3, 0x00, 0x60,
	0x5f, 0xc5, 0x43, 0xe8, 0x1b, 0xba, 0x67, 0x59, 0xee, 0x75, 0x6a, 0x5a, 0x16, 0x71, 0xec, 0xa1,
	0xd9, 0x27, 0x02, 0xc7, 0x20, 0x4e, 0xab, 0x1d, 0xd4, 0x9f, 0x69, 0x8b, 0xd7, 0x2d, 0x91, 0x3f,
	0x57, 0x3b, 0x0e, 0xfe, 0x17, 0x96, 0x53, 0x91, 0x0e, 0x7e, 0x82, 0x61, 0x23, 0x84, 0xfc, 0x31,
	0x57, 0x7d, 0xfe, 0x11, 0x1a, 0xd2, 0x59, 0xbb, 0xf6, 0x97, 0xbc, 0xfd, 0x0a, 0x00, 0x00, 0xff,
	0xff, 0x32, 0x6a, 0x6e, 0x3f, 0xab, 0x02, 0x00, 0x00,
}
