// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/login/login.proto

package go_micro_service_register

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginStatus int32

const (
	LoginStatus_Fail    LoginStatus = 0
	LoginStatus_Success LoginStatus = 1
)

var LoginStatus_name = map[int32]string{
	0: "Fail",
	1: "Success",
}

var LoginStatus_value = map[string]int32{
	"Fail":    0,
	"Success": 1,
}

func (x LoginStatus) String() string {
	return proto.EnumName(LoginStatus_name, int32(x))
}

func (LoginStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a27ccefc36a61526, []int{0}
}

type Request struct {
	Phone                string   `protobuf:"bytes,1,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Pwd                  string   `protobuf:"bytes,2,opt,name=Pwd,proto3" json:"Pwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_a27ccefc36a61526, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Request) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

type Response struct {
	Status               LoginStatus `protobuf:"varint,1,opt,name=Status,proto3,enum=go.micro.service.register.LoginStatus" json:"Status,omitempty"`
	Token                string      `protobuf:"bytes,2,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_a27ccefc36a61526, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatus() LoginStatus {
	if m != nil {
		return m.Status
	}
	return LoginStatus_Fail
}

func (m *Response) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterEnum("go.micro.service.register.LoginStatus", LoginStatus_name, LoginStatus_value)
	proto.RegisterType((*Request)(nil), "go.micro.service.register.Request")
	proto.RegisterType((*Response)(nil), "go.micro.service.register.Response")
}

func init() { proto.RegisterFile("proto/login/login.proto", fileDescriptor_a27ccefc36a61526) }

var fileDescriptor_a27ccefc36a61526 = []byte{
	// 231 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xcf, 0xc9, 0x4f, 0xcf, 0xcc, 0x83, 0x90, 0x7a, 0x60, 0x11, 0x21, 0xc9, 0xf4, 0x7c,
	0xbd, 0xdc, 0xcc, 0xe4, 0xa2, 0x7c, 0xbd, 0xe2, 0xd4, 0xa2, 0xb2, 0xcc, 0xe4, 0x54, 0xbd, 0xa2,
	0xd4, 0xf4, 0xcc, 0xe2, 0x92, 0xd4, 0x22, 0x25, 0x43, 0x2e, 0xf6, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4,
	0xe2, 0x12, 0x21, 0x11, 0x2e, 0xd6, 0x80, 0x8c, 0xfc, 0xbc, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d,
	0xce, 0x20, 0x08, 0x47, 0x48, 0x80, 0x8b, 0x39, 0xa0, 0x3c, 0x45, 0x82, 0x09, 0x2c, 0x06, 0x62,
	0x2a, 0x25, 0x70, 0x71, 0x04, 0xa5, 0x16, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0xd9, 0x71, 0xb1,
	0x05, 0x97, 0x24, 0x96, 0x94, 0x16, 0x83, 0x35, 0xf1, 0x19, 0xa9, 0xe9, 0xe1, 0xb4, 0x4a, 0xcf,
	0x07, 0xe4, 0x22, 0x88, 0xea, 0x20, 0xa8, 0x2e, 0x90, 0x9d, 0x21, 0xf9, 0xd9, 0xa9, 0x79, 0x50,
	0xf3, 0x21, 0x1c, 0x2d, 0x15, 0x2e, 0x6e, 0x24, 0xc5, 0x42, 0x1c, 0x5c, 0x2c, 0x6e, 0x89, 0x99,
	0x39, 0x02, 0x0c, 0x42, 0xdc, 0x5c, 0xec, 0xc1, 0xa5, 0xc9, 0xc9, 0xa9, 0xc5, 0xc5, 0x02, 0x8c,
	0x46, 0xeb, 0x18, 0xb9, 0x58, 0xc1, 0xca, 0x84, 0x82, 0x60, 0x0c, 0x25, 0x3c, 0xd6, 0x43, 0xbd,
	0x29, 0xa5, 0x8c, 0x57, 0x0d, 0xc4, 0x5f, 0x4a, 0x0c, 0x42, 0x81, 0x5c, 0x2c, 0x8e, 0xa5, 0x25,
	0x19, 0x54, 0x34, 0x32, 0x89, 0x0d, 0x1c, 0x1b, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff,
	0x1c, 0xa2, 0x6d, 0xa8, 0x01, 0x00, 0x00,
}
