// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/login/login.proto

package go_micro_service_register

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginStatus int32

const (
	LoginStatus_Fail    LoginStatus = 0
	LoginStatus_Success LoginStatus = 1
)

var LoginStatus_name = map[int32]string{
	0: "Fail",
	1: "Success",
}

var LoginStatus_value = map[string]int32{
	"Fail":    0,
	"Success": 1,
}

func (x LoginStatus) String() string {
	return proto.EnumName(LoginStatus_name, int32(x))
}

func (LoginStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a27ccefc36a61526, []int{0}
}

type AuthStatus int32

const (
	AuthStatus_AuthFail    AuthStatus = 0
	AuthStatus_AuthSuccess AuthStatus = 1
)

var AuthStatus_name = map[int32]string{
	0: "AuthFail",
	1: "AuthSuccess",
}

var AuthStatus_value = map[string]int32{
	"AuthFail":    0,
	"AuthSuccess": 1,
}

func (x AuthStatus) String() string {
	return proto.EnumName(AuthStatus_name, int32(x))
}

func (AuthStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a27ccefc36a61526, []int{1}
}

type Request struct {
	Phone                string   `protobuf:"bytes,1,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Pwd                  string   `protobuf:"bytes,2,opt,name=Pwd,proto3" json:"Pwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_a27ccefc36a61526, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Request) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

type Response struct {
	Status               LoginStatus `protobuf:"varint,1,opt,name=Status,proto3,enum=go.micro.service.register.LoginStatus" json:"Status,omitempty"`
	Token                string      `protobuf:"bytes,2,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_a27ccefc36a61526, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatus() LoginStatus {
	if m != nil {
		return m.Status
	}
	return LoginStatus_Fail
}

func (m *Response) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type AuthRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a27ccefc36a61526, []int{2}
}

func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (m *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(m, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type UserInfo struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Mobile               string   `protobuf:"bytes,3,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	AvatarUrl            string   `protobuf:"bytes,4,opt,name=Avatar_url,json=AvatarUrl,proto3" json:"Avatar_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a27ccefc36a61526, []int{3}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserInfo) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *UserInfo) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

type AuthResponse struct {
	Status               AuthStatus `protobuf:"varint,1,opt,name=Status,proto3,enum=go.micro.service.register.AuthStatus" json:"Status,omitempty"`
	User                 *UserInfo  `protobuf:"bytes,2,opt,name=User,proto3" json:"User,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a27ccefc36a61526, []int{4}
}

func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (m *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(m, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

func (m *AuthResponse) GetStatus() AuthStatus {
	if m != nil {
		return m.Status
	}
	return AuthStatus_AuthFail
}

func (m *AuthResponse) GetUser() *UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterEnum("go.micro.service.register.LoginStatus", LoginStatus_name, LoginStatus_value)
	proto.RegisterEnum("go.micro.service.register.AuthStatus", AuthStatus_name, AuthStatus_value)
	proto.RegisterType((*Request)(nil), "go.micro.service.register.Request")
	proto.RegisterType((*Response)(nil), "go.micro.service.register.Response")
	proto.RegisterType((*AuthRequest)(nil), "go.micro.service.register.AuthRequest")
	proto.RegisterType((*UserInfo)(nil), "go.micro.service.register.UserInfo")
	proto.RegisterType((*AuthResponse)(nil), "go.micro.service.register.AuthResponse")
}

func init() { proto.RegisterFile("proto/login/login.proto", fileDescriptor_a27ccefc36a61526) }

var fileDescriptor_a27ccefc36a61526 = []byte{
	// 373 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xc1, 0x4e, 0xea, 0x50,
	0x10, 0xa5, 0x50, 0xa0, 0x4c, 0x09, 0x8f, 0x4c, 0x5e, 0xde, 0xeb, 0x7b, 0x89, 0x89, 0x29, 0x8a,
	0x06, 0x93, 0x1a, 0x71, 0xe1, 0x4a, 0x13, 0x36, 0x26, 0x24, 0x6a, 0x48, 0x91, 0x85, 0x2b, 0x2d,
	0x65, 0x84, 0xc6, 0xd2, 0x8b, 0xf7, 0xb6, 0xf8, 0x07, 0x7e, 0x92, 0xdf, 0x67, 0x7a, 0x6f, 0xab,
	0x84, 0xc4, 0xb2, 0x21, 0x33, 0x73, 0xcf, 0x39, 0x73, 0xce, 0x50, 0xf8, 0xbb, 0xe2, 0x2c, 0x66,
	0xa7, 0x21, 0x9b, 0x07, 0x91, 0xfa, 0x75, 0xe4, 0x04, 0xff, 0xcd, 0x99, 0xb3, 0x0c, 0x7c, 0xce,
	0x1c, 0x41, 0x7c, 0x1d, 0xf8, 0xe4, 0x70, 0x9a, 0x07, 0x22, 0x26, 0x6e, 0x9f, 0x41, 0xdd, 0xa5,
	0xd7, 0x84, 0x44, 0x8c, 0xbf, 0xa1, 0x3a, 0x5a, 0xb0, 0x88, 0x2c, 0x6d, 0x5f, 0x3b, 0x6e, 0xb8,
	0xaa, 0xc1, 0x36, 0x54, 0x46, 0x6f, 0x33, 0xab, 0x2c, 0x67, 0x69, 0x69, 0x3f, 0x81, 0xe1, 0x92,
	0x58, 0xb1, 0x48, 0x10, 0x5e, 0x41, 0x6d, 0x1c, 0x7b, 0x71, 0x22, 0x24, 0xa9, 0xd5, 0xef, 0x3a,
	0x3f, 0xae, 0x72, 0x6e, 0x52, 0x47, 0x0a, 0xed, 0x66, 0xac, 0x74, 0xe7, 0x3d, 0x7b, 0xa1, 0x28,
	0xd3, 0x57, 0x8d, 0xdd, 0x01, 0x73, 0x90, 0xc4, 0x8b, 0x0d, 0x63, 0x0a, 0xa4, 0x6d, 0x82, 0x08,
	0x8c, 0x89, 0x20, 0x3e, 0x8c, 0x9e, 0x19, 0xb6, 0xa0, 0x3c, 0x9c, 0xc9, 0xe7, 0xaa, 0x5b, 0x1e,
	0xce, 0x10, 0x41, 0xbf, 0xf3, 0x96, 0x94, 0xa9, 0xca, 0x1a, 0xff, 0x40, 0xed, 0x96, 0x4d, 0x83,
	0x90, 0xac, 0x8a, 0x9c, 0x66, 0x1d, 0xee, 0x01, 0x0c, 0xd6, 0x5e, 0xec, 0xf1, 0xc7, 0x84, 0x87,
	0x96, 0x2e, 0xdf, 0x1a, 0x6a, 0x32, 0xe1, 0xa1, 0xfd, 0xae, 0x41, 0x53, 0x99, 0xc9, 0x22, 0x5f,
	0x6e, 0x45, 0x3e, 0x2c, 0x88, 0x9c, 0x12, 0xb7, 0x12, 0x5f, 0x80, 0x9e, 0xda, 0x96, 0xd6, 0xcc,
	0x7e, 0xa7, 0x80, 0x9c, 0xa7, 0x73, 0x25, 0xa1, 0x77, 0x00, 0xe6, 0xc6, 0x05, 0xd1, 0x00, 0xfd,
	0xda, 0x0b, 0xc2, 0x76, 0x09, 0x4d, 0xa8, 0x8f, 0x13, 0xdf, 0x27, 0x21, 0xda, 0x5a, 0xef, 0x04,
	0xe0, 0x7b, 0x29, 0x36, 0xc1, 0x48, 0xbb, 0x0c, 0xf8, 0x4b, 0x9d, 0xf5, 0x0b, 0xdc, 0xff, 0xd0,
	0xa0, 0x2a, 0x35, 0xd1, 0xcd, 0x0b, 0xbb, 0xc0, 0x50, 0xf6, 0x7f, 0xfc, 0xef, 0x14, 0x62, 0xd4,
	0x99, 0xec, 0x12, 0x3e, 0x80, 0x9e, 0xae, 0xc3, 0xee, 0x8e, 0x03, 0xe5, 0xb2, 0x47, 0x3b, 0x71,
	0xb9, 0xf4, 0xb4, 0x26, 0xbf, 0xeb, 0xf3, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3f, 0x39, 0xc8,
	0x86, 0xf2, 0x02, 0x00, 0x00,
}
