// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/register/register.proto

package go_micro_service_register

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterStatus int32

const (
	RegisterStatus_Fail    RegisterStatus = 0
	RegisterStatus_Success RegisterStatus = 1
)

var RegisterStatus_name = map[int32]string{
	0: "Fail",
	1: "Success",
}

var RegisterStatus_value = map[string]int32{
	"Fail":    0,
	"Success": 1,
}

func (x RegisterStatus) String() string {
	return proto.EnumName(RegisterStatus_name, int32(x))
}

func (RegisterStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_164fcd282674ab7a, []int{0}
}

type Request struct {
	CaptchaCode          string   `protobuf:"bytes,1,opt,name=CaptchaCode,proto3" json:"CaptchaCode,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Pwd                  string   `protobuf:"bytes,3,opt,name=Pwd,proto3" json:"Pwd,omitempty"`
	ConfirmPwd           string   `protobuf:"bytes,4,opt,name=ConfirmPwd,proto3" json:"ConfirmPwd,omitempty"`
	Uuid                 string   `protobuf:"bytes,5,opt,name=Uuid,proto3" json:"Uuid,omitempty"`
	SMSCode              string   `protobuf:"bytes,6,opt,name=SMSCode,proto3" json:"SMSCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_164fcd282674ab7a, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetCaptchaCode() string {
	if m != nil {
		return m.CaptchaCode
	}
	return ""
}

func (m *Request) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Request) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

func (m *Request) GetConfirmPwd() string {
	if m != nil {
		return m.ConfirmPwd
	}
	return ""
}

func (m *Request) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Request) GetSMSCode() string {
	if m != nil {
		return m.SMSCode
	}
	return ""
}

type Response struct {
	Status               RegisterStatus `protobuf:"varint,1,opt,name=Status,proto3,enum=go.micro.service.register.RegisterStatus" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_164fcd282674ab7a, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatus() RegisterStatus {
	if m != nil {
		return m.Status
	}
	return RegisterStatus_Fail
}

func init() {
	proto.RegisterEnum("go.micro.service.register.RegisterStatus", RegisterStatus_name, RegisterStatus_value)
	proto.RegisterType((*Request)(nil), "go.micro.service.register.Request")
	proto.RegisterType((*Response)(nil), "go.micro.service.register.Response")
}

func init() { proto.RegisterFile("proto/register/register.proto", fileDescriptor_164fcd282674ab7a) }

var fileDescriptor_164fcd282674ab7a = []byte{
	// 266 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xdf, 0x4a, 0xf3, 0x40,
	0x10, 0xc5, 0x9b, 0xaf, 0x69, 0xd2, 0x6f, 0x0a, 0x25, 0x0c, 0x5e, 0x44, 0x41, 0x29, 0xf1, 0xc2,
	0x3f, 0x17, 0x2b, 0xd4, 0x27, 0x90, 0x80, 0x77, 0x85, 0x92, 0xd0, 0x07, 0x58, 0x37, 0x63, 0xbb,
	0x60, 0xb3, 0x71, 0x77, 0xa3, 0xcf, 0xe3, 0x9b, 0x4a, 0x26, 0xad, 0xc4, 0x0b, 0x7b, 0x77, 0xe6,
	0xfc, 0xce, 0x70, 0x32, 0x59, 0xb8, 0x6c, 0xac, 0xf1, 0xe6, 0xc1, 0xd2, 0x56, 0x3b, 0x4f, 0xf6,
	0x47, 0x08, 0xf6, 0xf1, 0x7c, 0x6b, 0xc4, 0x5e, 0x2b, 0x6b, 0x84, 0x23, 0xfb, 0xa1, 0x15, 0x89,
	0x63, 0x20, 0xfb, 0x0a, 0x20, 0x2e, 0xe8, 0xbd, 0x25, 0xe7, 0x71, 0x01, 0xb3, 0x5c, 0x36, 0x5e,
	0xed, 0x64, 0x6e, 0x2a, 0x4a, 0x83, 0x45, 0x70, 0xfb, 0xbf, 0x18, 0x5a, 0x78, 0x06, 0x93, 0xf5,
	0xce, 0xd4, 0x94, 0xfe, 0x63, 0xd6, 0x0f, 0x98, 0xc0, 0x78, 0xfd, 0x59, 0xa5, 0x63, 0xf6, 0x3a,
	0x89, 0x57, 0x00, 0xb9, 0xa9, 0x5f, 0xb5, 0xdd, 0x77, 0x20, 0x64, 0x30, 0x70, 0x10, 0x21, 0xdc,
	0xb4, 0xba, 0x4a, 0x27, 0x4c, 0x58, 0x63, 0x0a, 0x71, 0xb9, 0x2a, 0xb9, 0x39, 0x62, 0xfb, 0x38,
	0x66, 0x2b, 0x98, 0x16, 0xe4, 0x1a, 0x53, 0x3b, 0xc2, 0x27, 0x88, 0x4a, 0x2f, 0x7d, 0xeb, 0xf8,
	0xf3, 0xe6, 0xcb, 0x3b, 0xf1, 0xe7, 0x6d, 0xa2, 0x38, 0x88, 0x7e, 0xa1, 0x38, 0x2c, 0xde, 0xdf,
	0xc0, 0xfc, 0x37, 0xc1, 0x29, 0x84, 0xcf, 0x52, 0xbf, 0x25, 0x23, 0x9c, 0x41, 0x5c, 0xb6, 0x4a,
	0x91, 0x73, 0x49, 0xb0, 0x94, 0x5d, 0x6f, 0x1f, 0xc4, 0xcd, 0x40, 0x67, 0x27, 0x3b, 0xf9, 0x5f,
	0x5e, 0x5c, 0x9f, 0xcc, 0xf4, 0xc7, 0x64, 0xa3, 0x97, 0x88, 0x1f, 0xe8, 0xf1, 0x3b, 0x00, 0x00,
	0xff, 0xff, 0xae, 0x81, 0xfd, 0x26, 0xc1, 0x01, 0x00, 0x00,
}
