// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/register/register.proto

package go_micro_service_register

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterStatus int32

const (
	RegisterStatus_RegisterFail    RegisterStatus = 0
	RegisterStatus_RegisterSuccess RegisterStatus = 1
)

var RegisterStatus_name = map[int32]string{
	0: "RegisterFail",
	1: "RegisterSuccess",
}

var RegisterStatus_value = map[string]int32{
	"RegisterFail":    0,
	"RegisterSuccess": 1,
}

func (x RegisterStatus) String() string {
	return proto.EnumName(RegisterStatus_name, int32(x))
}

func (RegisterStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_164fcd282674ab7a, []int{0}
}

type RegisterRequest struct {
	CaptchaCode          string   `protobuf:"bytes,1,opt,name=CaptchaCode,proto3" json:"CaptchaCode,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Pwd                  string   `protobuf:"bytes,3,opt,name=Pwd,proto3" json:"Pwd,omitempty"`
	ConfirmPwd           string   `protobuf:"bytes,4,opt,name=ConfirmPwd,proto3" json:"ConfirmPwd,omitempty"`
	Uuid                 string   `protobuf:"bytes,5,opt,name=Uuid,proto3" json:"Uuid,omitempty"`
	SMSCode              string   `protobuf:"bytes,6,opt,name=SMSCode,proto3" json:"SMSCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_164fcd282674ab7a, []int{0}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetCaptchaCode() string {
	if m != nil {
		return m.CaptchaCode
	}
	return ""
}

func (m *RegisterRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *RegisterRequest) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

func (m *RegisterRequest) GetConfirmPwd() string {
	if m != nil {
		return m.ConfirmPwd
	}
	return ""
}

func (m *RegisterRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *RegisterRequest) GetSMSCode() string {
	if m != nil {
		return m.SMSCode
	}
	return ""
}

type RegisterResponse struct {
	RegisterStatus       RegisterStatus `protobuf:"varint,1,opt,name=RegisterStatus,proto3,enum=go.micro.service.register.RegisterStatus" json:"RegisterStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_164fcd282674ab7a, []int{1}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetRegisterStatus() RegisterStatus {
	if m != nil {
		return m.RegisterStatus
	}
	return RegisterStatus_RegisterFail
}

func init() {
	proto.RegisterEnum("go.micro.service.register.RegisterStatus", RegisterStatus_name, RegisterStatus_value)
	proto.RegisterType((*RegisterRequest)(nil), "go.micro.service.register.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "go.micro.service.register.RegisterResponse")
}

func init() { proto.RegisterFile("proto/register/register.proto", fileDescriptor_164fcd282674ab7a) }

var fileDescriptor_164fcd282674ab7a = []byte{
	// 272 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xdf, 0x4a, 0xf3, 0x40,
	0x10, 0xc5, 0x9b, 0xaf, 0x7f, 0x3e, 0x1d, 0xa5, 0x86, 0xd1, 0x8b, 0x55, 0x50, 0x4a, 0xae, 0xb4,
	0xc2, 0x0a, 0xf5, 0xc2, 0x07, 0x08, 0x78, 0x27, 0xd4, 0x04, 0x1f, 0x20, 0x6e, 0xc6, 0x76, 0xc1,
	0x66, 0xd3, 0xdd, 0x8d, 0x3e, 0x93, 0x6f, 0x29, 0x9d, 0x76, 0x6d, 0x2c, 0x08, 0xbd, 0x3b, 0xf3,
	0x3b, 0x93, 0xc9, 0x99, 0x59, 0xb8, 0xac, 0xad, 0xf1, 0xe6, 0xce, 0xd2, 0x4c, 0x3b, 0x4f, 0xf6,
	0x47, 0x48, 0xe6, 0x78, 0x3e, 0x33, 0x72, 0xa1, 0x95, 0x35, 0xd2, 0x91, 0xfd, 0xd0, 0x8a, 0x64,
	0x68, 0x48, 0xbe, 0x22, 0x38, 0xc9, 0x36, 0x45, 0x46, 0xcb, 0x86, 0x9c, 0xc7, 0x11, 0x1c, 0xa5,
	0x45, 0xed, 0xd5, 0xbc, 0x48, 0x4d, 0x49, 0x22, 0x1a, 0x45, 0xd7, 0x87, 0x59, 0x1b, 0xe1, 0x19,
	0xf4, 0xa7, 0x73, 0x53, 0x91, 0xf8, 0xc7, 0xde, 0xba, 0xc0, 0x18, 0xba, 0xd3, 0xcf, 0x52, 0x74,
	0x99, 0xad, 0x24, 0x5e, 0x01, 0xa4, 0xa6, 0x7a, 0xd3, 0x76, 0xb1, 0x32, 0x7a, 0x6c, 0xb4, 0x08,
	0x22, 0xf4, 0x5e, 0x1a, 0x5d, 0x8a, 0x3e, 0x3b, 0xac, 0x51, 0xc0, 0xff, 0xfc, 0x29, 0xe7, 0x3f,
	0x0f, 0x18, 0x87, 0x32, 0x21, 0x88, 0xb7, 0x51, 0x5d, 0x6d, 0x2a, 0x47, 0xf8, 0x0c, 0xc3, 0xc0,
	0x72, 0x5f, 0xf8, 0xc6, 0x71, 0xdc, 0xe1, 0xe4, 0x46, 0xfe, 0xb9, 0xb3, 0xfc, 0xfd, 0x41, 0xb6,
	0x33, 0x60, 0xfc, 0xb0, 0x3b, 0x12, 0x63, 0x38, 0x0e, 0xe4, 0xb1, 0xd0, 0xef, 0x71, 0x07, 0x4f,
	0xb7, 0x57, 0xcb, 0x1b, 0xa5, 0xc8, 0xb9, 0x38, 0x9a, 0x2c, 0xe1, 0x20, 0x40, 0xa4, 0x96, 0x1e,
	0xef, 0x91, 0x65, 0x73, 0xfb, 0x8b, 0xdb, 0xbd, 0x7a, 0xd7, 0xcb, 0x27, 0x9d, 0xd7, 0x01, 0x3f,
	0xf0, 0xfd, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x27, 0x19, 0x31, 0x23, 0x01, 0x02, 0x00, 0x00,
}
